import { THREE } from '../vendor/three.js';

const mat=(color,rough=.82,metal=.04)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal});
const basic=(color,opacity=.1)=>new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide});
const add=(g,geo,m,pos=[0,0,0],rot=[0,0,0])=>{const x=new THREE.Mesh(geo,m);x.position.set(...pos);x.rotation.set(...rot);x.receiveShadow=true;x.castShadow=false;g.add(x);return x};
function signTexture(name,archetype,accent){const c=document.createElement('canvas');c.width=1024;c.height=256;const x=c.getContext('2d');x.fillStyle='#09090b';x.fillRect(0,0,c.width,c.height);x.fillStyle='#141418';for(let i=0;i<18;i++)x.fillRect(i*64,0,1,c.height);x.fillStyle=`#${new THREE.Color(accent).getHexString()}`;x.fillRect(0,0,18,c.height);x.fillRect(0,226,c.width,8);x.fillStyle='#eee8df';x.font='900 88px Impact, Arial Black, sans-serif';x.textBaseline='middle';x.fillText(String(name||'TWEAKIN').toUpperCase(),52,108);x.fillStyle='#9f9890';x.font='700 27px Arial, sans-serif';x.fillText(`TWEAKIN FIGHT WORLD  //  ${String(archetype||'VENUE').toUpperCase()}`,56,190);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}

export function addArenaBeauty(arena){
  if(!arena?.venue||arena.beautyLayer)return;const d=arena.def,s=d.size*.5,g=new THREE.Group();g.name='arena-beauty';arena.venue.add(g);arena.beautyLayer=g;arena.beautyLights=[];arena.beautyPuddles=[];
  const accent=d.lightB??0xb21b25,warm=d.lightA??0xe7c4a1;
  for(let i=0;i<12;i++){const a=(i/12)*Math.PI*2+(i%3)*.31,r=.55+(i%5)*.58,x=Math.cos(a)*r,z=Math.sin(a)*r,ring=add(g,new THREE.RingGeometry(.18+(i%3)*.08,.22+(i%3)*.10,24),basic(i%2?0x5a4b43:0x4b1b1d,.025+(i%4)*.006),[x,.018,z],[-Math.PI/2,0,a]);ring.scale.set(1.5,.65,1);}
  for(let i=0;i<8;i++){const x=(i-3.5)*.68,z=((i*37)%5-2)*.48;add(g,new THREE.PlaneGeometry(.46+(i%2)*.25,.018),basic(0xc4b6a6,.022),[x,.021,z],[-Math.PI/2,0,(i-3)*.25]);}
  const wet=new THREE.MeshPhysicalMaterial({color:0x222126,roughness:.18,metalness:.04,clearcoat:.65,clearcoatRoughness:.14,transparent:true,opacity:.38});for(let i=0;i<4;i++){const puddle=add(g,new THREE.CircleGeometry(.38+i*.06,28),wet.clone(),[(i-1.5)*1.35,.024,-.7+(i%2)*1.45],[-Math.PI/2,0,0]);puddle.scale.set(1.6,.55,1);arena.beautyPuddles.push(puddle);}
  for(const [x,z,c] of [[-s*.62,-s*.55,warm],[s*.62,-s*.55,accent],[-s*.55,s*.55,accent],[s*.55,s*.55,warm]]){const pool=add(g,new THREE.CircleGeometry(.82,30),basic(c,.035),[x,.025,z],[-Math.PI/2,0,0]);pool.scale.set(1,.62,1);}
  const practicalMat=color=>{const m=mat(color,.35,.12);m.emissive=new THREE.Color(color);m.emissiveIntensity=.9;return m};
  for(let i=0;i<6;i++){const a=i/6*Math.PI*2+.25,x=Math.cos(a)*s*.86,z=Math.sin(a)*s*.86,c=i%2?accent:warm;const stem=add(g,new THREE.CylinderGeometry(.018,.018,1.55,6),mat(0x27282b,.55,.55),[x,.80,z]);stem.rotation.z=i%2?-.05:.05;add(g,new THREE.CapsuleGeometry(.035,.34,5,8),practicalMat(c),[x,1.50,z],[0,0,stem.rotation.z]);if(i%2===0){const l=new THREE.PointLight(c,2.4,3.6,2);l.position.set(x,1.45,z);g.add(l);arena.beautyLights.push(l);}}
  const signMat=new THREE.MeshBasicMaterial({map:signTexture(d.name,d.archetype,accent),transparent:true,opacity:.92,toneMapped:false});const sign=add(g,new THREE.PlaneGeometry(Math.min(5.8,s*1.35),1.45),signMat,[0,2.42,-s*.935],[0,0,0]);sign.userData.venueSign=true;const signGlow=new THREE.PointLight(accent,5.5,6.8,2);signGlow.position.set(0,2.3,-s*.62);g.add(signGlow);arena.beautyLights.push(signGlow);arena.beautySignGlow=signGlow;
  const dark=mat(0x08080a,.92,.02);for(let i=0;i<6;i++){const a=-1.0+i*.4,x=Math.sin(a)*s*1.10,z=Math.cos(a)*s*1.10,h=.65+(i%3)*.24;const crate=add(g,new THREE.BoxGeometry(.42+(i%2)*.18,h,.48),dark,[x,h*.5,z],[0,a*.12,0]);crate.userData.foreground=true;}
  const cable=mat(0x151519,.76,.35);for(let i=-2;i<=2;i++){const bar=add(g,new THREE.CylinderGeometry(.012,.012,s*1.28,6),cable,[i*s*.18,3.45,-s*.28],[Math.PI/2,0,.08*i]);bar.castShadow=false;}
  arena.beautyUpdate=(dt,t)=>{const pulse=.5+.5*Math.sin(t*.72);g.traverse(o=>{if(o.isMesh&&o.material?.emissiveIntensity>0)o.material.emissiveIntensity=.72+pulse*.28;});if(arena.beautySignGlow)arena.beautySignGlow.intensity=(arena.beautySignGlow.userData.baseIntensity??4.6)+pulse*(arena.beautySignGlow.userData.pulseIntensity??1.8);sign.material.opacity=.88+pulse*.08;};
}
export function setArenaBeautyQuality(arena,q='medium',mobile=false){if(!arena?.beautyLayer)return;const low=q==='low',medium=q==='medium';arena.beautyPuddles?.forEach((p,i)=>p.visible=!low&&(!mobile||!medium||i<2));arena.beautyLights?.forEach((l,i)=>{const keep=!low&&(!mobile||q==='high'||i===arena.beautyLights.length-1);l.visible=keep;if(l===arena.beautySignGlow){l.userData.baseIntensity=mobile?3.0:4.6;l.userData.pulseIntensity=mobile?.9:1.8;}});}
export function updateArenaBeauty(arena,dt,t){arena?.beautyUpdate?.(dt,t)}
