import { THREE } from '../vendor/three.js';
import { EMPTY_INPUT } from '../core/types.js';
import { InputManager } from './Input.js';
import { CinematicCombatMatch } from './CinematicCombatMatch.js';
import { PresentationDirector } from './PresentationDirector.js';
import { MenuBackdrop } from './MenuBackdrop.js';
import { DOMFX } from './DOMFX.js';
import { PostFX } from './PostFX.js';
import { PerformanceGovernor } from './PerformanceGovernor.js';
import { ArenaAtmosphere } from './ArenaAtmosphere.js';
import { CombatLighting } from './CombatLighting.js';
import { AudioEngine } from '../audio/AudioEngine.js';
export class Game {
  renderer;camera;input=new InputManager();audio=new AudioEngine();match=null;presentation=null;menuBackdrop=null;domfx=null;postFX=null;governor=null;atmosphere=null;combatLighting=null;runtimeQuality='medium';settings;net=null;running=true;acc=0;prev=performance.now()/1000;fps=60;fpsAccum=0;fpsFrames=0;errors=[];hooks={};host;raf=0;fixed=1/60;pause=false;lastSnapshotSend=0;slowmoTimer=0;slowmoScale=1;mobile=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0||innerWidth<900;
  constructor(host,settings){
    this.host=host;this.settings=settings;this.runtimeQuality=settings.quality;this.renderer=new THREE.WebGLRenderer({antialias:settings.quality!=='low',powerPreference:'high-performance',alpha:false,stencil:false});this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.06;host.innerHTML='';host.appendChild(this.renderer.domElement);this.camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.06,100);this.camera.position.set(0,5.4,8);this.presentation=new PresentationDirector(this.renderer,this.camera,this.mobile);this.menuBackdrop=new MenuBackdrop(this.mobile);this.domfx=new DOMFX();this.postFX=new PostFX(this.renderer,this.mobile,settings.quality);this.governor=new PerformanceGovernor({mobile:this.mobile,quality:settings.quality,onChange:q=>this.applyRuntimeQuality(q)});this.applyRuntimeQuality(settings.quality);addEventListener('resize',()=>this.resize());addEventListener('error',e=>this.errors.push(String(e.message)));this.audio.setVolumes(settings.masterVolume,settings.musicVolume,settings.sfxVolume);this.loop();
  }
  dprFor(q){if(this.mobile)return q==='high'?1.35:q==='medium'?1.18:.9;return q==='high'?2:q==='medium'?1.5:1.1}
  applyRuntimeQuality(q){this.runtimeQuality=q;this.renderer.shadowMap.enabled=q!=='low';this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.dprFor(q)));this.renderer.setSize(innerWidth,innerHeight,false);this.postFX?.setQuality(q);this.postFX?.resize(innerWidth,innerHeight)}
  setHooks(h){this.hooks=h}
  hapticImpact(kind,blocked){if(!this.mobile)return;const ms=blocked?7:kind==='special'?34:kind==='environment'?28:(kind==='heavy'||kind==='weapon'||kind==='grapple')?18:9;try{navigator.vibrate?.(ms)}catch{}}
  triggerSlowmo(kind,blocked){if(blocked||this.settings.reducedMotion)return;const major=kind==='special'||kind==='environment',strong=major||kind==='heavy'||kind==='weapon'||kind==='grapple';if(!strong)return;this.slowmoTimer=Math.max(this.slowmoTimer,major?.22:.10);this.slowmoScale=major?.34:.58;}
  start(config){this.combatLighting?.dispose();this.atmosphere?.dispose();this.presentation?.dispose();this.match?.dispose();this.match=new CinematicCombatMatch(config,this.audio,{onMessage:(t,d)=>this.hooks.onMessage?.(t,d),onKO:()=>{},onEnd:()=>this.hooks.onEnd?.(this.match),onSpecial:(f,n)=>{this.audio.special?.();this.hooks.onSpecial?.(f.def.name,n)},onImpact:(pos,kind,blocked,a,t)=>{this.presentation?.impact(pos,kind,blocked,a,t);this.domfx?.hit(kind,blocked);this.hapticImpact(kind,blocked);this.triggerSlowmo(kind,blocked)}});this.presentation?.attach(this.match);this.atmosphere=new ArenaAtmosphere(this.match,this.mobile||this.runtimeQuality==='low');this.combatLighting=new CombatLighting(this.match,this.mobile||this.runtimeQuality==='low');this.domfx?.intro(this.match);this.audio.startMusic();this.audio.setIntensity(.28);this.acc=0;this.pause=false;this.slowmoTimer=0;this.slowmoScale=1;this.renderer.domElement.focus?.()}
  stop(){this.combatLighting?.dispose();this.combatLighting=null;this.atmosphere?.dispose();this.atmosphere=null;this.presentation?.dispose();this.match?.dispose();this.match=null;this.domfx?.clear();this.audio.stopMusic();this.slowmoTimer=0;this.slowmoScale=1}
  setPaused(v){this.pause=v}setNetwork(net){this.net=net}
  loop=()=>{
    if(!this.running)return;this.raf=requestAnimationFrame(this.loop);const now=performance.now()/1000,dt=Math.min(.1,now-this.prev);this.prev=now;this.fpsAccum+=dt;this.fpsFrames++;if(this.fpsAccum>.5){this.fps=this.fpsFrames/this.fpsAccum;this.fpsAccum=0;this.fpsFrames=0}this.governor?.sample(this.fps,dt);this.audio.update();if(this.slowmoTimer>0){this.slowmoTimer=Math.max(0,this.slowmoTimer-dt);if(!this.slowmoTimer)this.slowmoScale=1}
    if(!this.pause&&this.match){const simDt=dt*this.slowmoScale;this.acc+=simDt;let steps=0;while(this.acc>=this.fixed&&steps<5){this.step(this.fixed);this.acc-=this.fixed;steps++}this.match.tickCinematic(dt);this.presentation?.update(dt);this.atmosphere?.update(dt);this.updateMusicIntensity();this.updateCamera(dt);this.combatLighting?.update(dt,this.camera);this.postFX.render(this.match.scene,this.camera,dt,this.match.cameraShake,Math.min(1,this.match.cinematicTime)+(this.slowmoTimer>0?.12:0));this.hooks.onHud?.(this.match)}else if(!this.match){this.camera.fov+=(47-this.camera.fov)*(1-Math.exp(-dt*4));this.camera.updateProjectionMatrix();this.menuBackdrop?.update(dt,this.camera);this.renderer.toneMappingExposure=1.02;this.postFX.render(this.menuBackdrop.scene,this.camera,dt,0,.14)}this.input.endFrame();this.exposeDebug();
  };
  updateMusicIntensity(){if(!this.match)return;const fs=this.match.fighters;if(!fs.length)return;const danger=fs.reduce((n,f)=>n+(100-Math.min(f.physical,f.consciousness))/100,0)/fs.length,combo=Math.max(...fs.map(f=>f.combo||0),0);this.audio.setIntensity?.(Math.min(1,.2+danger*.58+Math.min(.22,combo*.025)+(this.match.cinematicTime>0?.2:0)))}
  step(dt){if(!this.match)return;const inputs=this.match.fighters.map(()=>({...EMPTY_INPUT}));for(const slot of this.match.config.humanSlots){if(this.net){const mine=this.net.localSlot;if(slot===mine)inputs[slot]=this.input.frame(0);else inputs[slot]=this.net.getRemoteInput(slot)}else inputs[slot]=this.input.frame(slot)}if(this.net){this.net.sendLocalInput(inputs[this.net.localSlot]??{...EMPTY_INPUT},this.match.frame);if(this.net.isHost){this.match.update(dt,inputs);this.lastSnapshotSend+=dt;if(this.lastSnapshotSend>1/20){this.lastSnapshotSend=0;this.net.broadcastSnapshot({frame:this.match.frame,remaining:this.match.remaining,fighters:this.match.snapshots()})}}else{const snap=this.net.consumeSnapshot();if(snap){this.match.remaining=snap.remaining;this.match.applySnapshots(snap.fighters)}}}else this.match.update(dt,inputs)}
  updateCamera(dt){
    if(!this.match)return;const target=this.match.getCameraTarget();let tx=target.x,tz=target.z,ty=target.y,distance=target.distance,angle=0,fov=44,height=3.15+distance*.22,intro=this.match.introTime>0;
    if(intro&&this.match.fighters.length>=2){const a=this.match.fighters[0],b=this.match.fighters[1],p=1-this.match.introTime/Math.max(.01,this.match.introDuration||1.22);if(p<.34){tx=a.group.position.x;tz=a.group.position.z;angle=a.yaw+.78;distance=2.65;height=2.2;ty=1.48;fov=34}else if(p<.68){tx=b.group.position.x;tz=b.group.position.z;angle=b.yaw-.78;distance=2.65;height=2.2;ty=1.48;fov=34}else{tx=(a.group.position.x+b.group.position.x)/2;tz=(a.group.position.z+b.group.position.z)/2;angle=Math.atan2(b.group.position.x-a.group.position.x,b.group.position.z-a.group.position.z)+Math.PI/2;if(Math.cos(angle)<0)angle+=Math.PI;distance=5.45;height=3.5;ty=1.3;fov=40}}
    else if(target.cinematic){const[a,b]=target.cinematic;tx=(a.group.position.x+b.group.position.x)/2;tz=(a.group.position.z+b.group.position.z)/2;const c=this.match.cinematicTime,p=1-Math.min(1,c/1.45);if(p<.24){distance=3.35;angle=a.yaw+.48;fov=35;height=2.55}else if(p<.5){distance=4.45;angle=a.yaw-1.10;fov=33;height=1.72}else if(p<.76){distance=3.15;angle=a.yaw+2.38;fov=38;height=2.14}else{distance=4.8;angle=a.yaw+.12;fov=31;height=2.85}angle+=Math.sin(c*4)*.025;ty=1.38;}
    else if(this.match.fighters.length>2){angle=this.match.elapsed*.035+Math.PI*.5;distance=Math.max(distance,7.2);fov=49;height=4.55;ty=1.2;}
    else if(this.match.fighters[0]&&this.match.fighters[1]){const a=this.match.fighters[0],b=this.match.fighters[1];angle=Math.atan2(b.group.position.x-a.group.position.x,b.group.position.z-a.group.position.z)+Math.PI/2;if(Math.cos(angle)<0)angle+=Math.PI;const edge=Math.max(Math.abs(tx),Math.abs(tz))/(this.match.arena?.def?.size*.5||5);distance=Math.max(distance,this.mobile?6.05:5.5);if(edge>.66){angle+=Math.sin(this.match.elapsed*.7)*.05;distance=Math.max(5.8,distance);height+=.1;fov=43}else fov=43+Math.min(7,(distance-5.2)*1.25)}
    const portrait=innerHeight>innerWidth*1.18;if(portrait){distance*=1.72;height+=1.08;fov=Math.max(fov,55);ty+=.16}
    const shake=this.settings.reducedMotion?0:this.match.cameraShake*this.settings.cameraShake,sx=(Math.random()-.5)*shake*.19,sy=(Math.random()-.5)*shake*.14,desired=new THREE.Vector3(tx+Math.sin(angle)*distance+sx,height+sy,tz+Math.cos(angle)*distance+sx);this.camera.position.lerp(desired,1-Math.exp(-dt*(target.cinematic||intro?10:5.4)));this.camera.fov+=(fov-this.camera.fov)*(1-Math.exp(-dt*9));this.camera.updateProjectionMatrix();this.camera.lookAt(new THREE.Vector3(tx,ty,tz));
  }
  resize(){const w=innerWidth,h=innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.dprFor(this.runtimeQuality)));this.postFX?.resize(w,h)}
  updateSettings(s){this.settings=s;this.audio.setVolumes(s.masterVolume,s.musicVolume,s.sfxVolume);this.governor.requested=s.quality;this.applyRuntimeQuality(s.quality);this.resize()}
  exposeDebug(){const d=this.match?.debug(this.fps,this.errors.slice(-10),this.net?.debug()??{})??{mode:'menu',arena:'',fps:this.fps,errors:this.errors.slice(-10),network:this.net?.debug()??{},fighters:[],frame:0};d.performance=this.governor?.debug?.()??{};d.slowmo={active:this.slowmoTimer>0,scale:this.slowmoScale};d.lighting={active:!!this.combatLighting};window.__TWEAKIN_DEBUG__=d;window.__TWEAKIN_GAME__=this}
  destroy(){this.running=false;cancelAnimationFrame(this.raf);this.stop();this.menuBackdrop?.dispose();this.postFX?.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}
