import { clamp } from '../core/math.js';
export class AudioEngine {
  ctx=null;master=null;sfx=null;music=null;verb=null;verbGain=null;compressor=null;musicOn=false;nextBeat=0;beatIndex=0;intensity=.25;targetIntensity=.25;volumes={master:.8,music:.35,sfx:.8};
  init(){
    if(this.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.sfx=this.ctx.createGain();this.music=this.ctx.createGain();this.verb=this.ctx.createConvolver();this.verbGain=this.ctx.createGain();this.compressor=this.ctx.createDynamicsCompressor();
    this.compressor.threshold.value=-18;this.compressor.knee.value=14;this.compressor.ratio.value=5;this.compressor.attack.value=.004;this.compressor.release.value=.16;this.verbGain.gain.value=.16;this.verb.buffer=this.makeImpulse(1.15,2.4);
    this.sfx.connect(this.master);this.sfx.connect(this.verb);this.verb.connect(this.verbGain);this.verbGain.connect(this.master);this.music.connect(this.master);this.master.connect(this.compressor);this.compressor.connect(this.ctx.destination);this.applyVolumes();
  }
  makeImpulse(seconds,decay){const n=Math.max(1,Math.floor(this.ctx.sampleRate*seconds)),b=this.ctx.createBuffer(2,n,this.ctx.sampleRate);for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/n,decay)}return b}
  resume(){this.init();this.ctx?.resume?.()}
  setVolumes(master,music,sfx){this.volumes={master:clamp(master,0,1),music:clamp(music,0,1),sfx:clamp(sfx,0,1)};this.applyVolumes()}
  setIntensity(v){this.targetIntensity=clamp(v,0,1)}
  applyVolumes(){if(!this.master||!this.sfx||!this.music)return;this.master.gain.value=this.volumes.master;this.sfx.gain.value=this.volumes.sfx;this.music.gain.value=this.volumes.music}
  tone(freq=100,duration=.08,amount=.2,type='sine',dest=null,pan=0){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner?.();o.type=type;o.frequency.setValueAtTime(freq,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(24,freq*.55),this.ctx.currentTime+duration);g.gain.setValueAtTime(Math.max(.001,amount),this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+duration);o.connect(g);if(p){p.pan.value=clamp(pan,-1,1);g.connect(p);p.connect(dest??this.sfx)}else g.connect(dest??this.sfx);o.start();o.stop(this.ctx.currentTime+duration)}
  noise(duration=.08,amount=.25,filterFreq=500,pan=0){if(!this.ctx||!this.sfx)return;const n=Math.max(1,Math.floor(this.ctx.sampleRate*duration)),buf=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner?.();src.buffer=buf;f.type='lowpass';f.frequency.value=filterFreq;g.gain.value=amount;src.connect(f);f.connect(g);if(p){p.pan.value=clamp(pan,-1,1);g.connect(p);p.connect(this.sfx)}else g.connect(this.sfx);src.start()}
  ui(select=false){this.resume();this.tone(select?115:180,.045,.08,'square')}
  hit(kind='light',pan=0){this.resume();const k={light:[.06,.15,760,120],heavy:[.11,.32,420,74],grapple:[.14,.28,280,58],special:[.18,.45,600,42],environment:[.16,.4,240,50],weapon:[.12,.36,1300,88]}[kind]??[.08,.2,600,90];this.noise(k[0],k[1],k[2],pan);this.tone(k[3],k[0]*1.5,k[1]*.7,'triangle',null,pan);if(kind==='heavy'||kind==='special'||kind==='environment')this.tone(kind==='special'?36:48,.22,k[1]*.22,'sine')}
  impact(kind='light',blocked=false,pan=0){this.hit(blocked?'light':kind,pan);if(blocked){this.tone(410,.035,.05,'square',null,pan);this.noise(.035,.07,2400,pan)}}
  pickup(){this.resume();this.tone(330,.05,.08,'square');setTimeout(()=>this.tone(440,.05,.07,'square'),45)}
  environment(){this.hit('environment')}
  ko(){this.resume();this.tone(70,.6,.5,'sawtooth');this.noise(.32,.2,180);setTimeout(()=>this.tone(44,.8,.35,'triangle'),90)}
  win(){this.ko();setTimeout(()=>{this.tone(132,.5,.2,'triangle');this.tone(198,.65,.11,'sine')},260)}
  special(){this.resume();this.tone(55,.7,.28,'sawtooth');this.tone(110,.45,.18,'square');this.noise(.24,.12,1300)}
  crowd(intensity=.4){this.resume();this.noise(.2,.08+intensity*.11,900)}
  startMusic(){this.resume();this.musicOn=true;this.nextBeat=this.ctx?.currentTime??0;this.beatIndex=0}
  stopMusic(){this.musicOn=false}
  update(){if(!this.ctx)return;this.intensity+=(this.targetIntensity-this.intensity)*.035;if(!this.musicOn||!this.music)return;const now=this.ctx.currentTime,step=.52-this.intensity*.09;while(this.nextBeat<now+.12){const beat=this.beatIndex%8;this.kickAt(this.nextBeat,beat%4===0?.2+.05*this.intensity:.10+.04*this.intensity);if(beat%2===1)this.hatAt(this.nextBeat+step*.5);if(beat===2||beat===6)this.snareAt(this.nextBeat);if(beat%4===0)this.bassAt(this.nextBeat,beat===0?55:49);if(this.intensity>.62&&beat%2===0)this.hatAt(this.nextBeat+step*.25,.65);this.nextBeat+=step;this.beatIndex++}}
  kickAt(t,a){if(!this.ctx||!this.music)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(110,t);o.frequency.exponentialRampToValueAtTime(42,t+.13);g.gain.setValueAtTime(a,t);g.gain.exponentialRampToValueAtTime(.001,t+.14);o.connect(g);g.connect(this.music);o.start(t);o.stop(t+.15)}
  hatAt(t,mul=1){if(!this.ctx||!this.music)return;const n=512,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=Math.random()*2-1;const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='highpass';f.frequency.value=5000;g.gain.setValueAtTime(.035*mul,t);g.gain.exponentialRampToValueAtTime(.001,t+.04);s.connect(f);f.connect(g);g.connect(this.music);s.start(t)}
  snareAt(t){if(!this.ctx||!this.music)return;const n=Math.floor(this.ctx.sampleRate*.09),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=1600;g.gain.value=.07+.03*this.intensity;s.connect(f);f.connect(g);g.connect(this.music);s.start(t)}
  bassAt(t,freq){if(!this.ctx||!this.music)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o.frequency.value=freq;f.type='lowpass';f.frequency.value=180+this.intensity*160;g.gain.setValueAtTime(.025+.03*this.intensity,t);g.gain.exponentialRampToValueAtTime(.001,t+.38);o.connect(f);f.connect(g);g.connect(this.music);o.start(t);o.stop(t+.4)}
}
