import { clamp } from '../core/math.js';
export class AudioEngine {
  ctx=null;master=null;sfx=null;music=null;verb=null;verbGain=null;compressor=null;musicOn=false;nextBeat=0;beatIndex=0;intensity=.25;targetIntensity=.25;volumes={master:.8,music:.35,sfx:.8};
  init(){if(this.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.sfx=this.ctx.createGain();this.music=this.ctx.createGain();this.verb=this.ctx.createConvolver();this.verbGain=this.ctx.createGain();this.compressor=this.ctx.createDynamicsCompressor();this.compressor.threshold.value=-18;this.compressor.knee.value=14;this.compressor.ratio.value=5;this.compressor.attack.value=.004;this.compressor.release.value=.16;this.verbGain.gain.value=.14;this.verb.buffer=this.makeImpulse(1.15,2.4);this.sfx.connect(this.master);this.sfx.connect(this.verb);this.verb.connect(this.verbGain);this.verbGain.connect(this.master);this.music.connect(this.master);this.master.connect(this.compressor);this.compressor.connect(this.ctx.destination);this.applyVolumes();}
  makeImpulse(seconds,decay){const n=Math.max(1,Math.floor(this.ctx.sampleRate*seconds)),b=this.ctx.createBuffer(2,n,this.ctx.sampleRate);for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/n,decay)}return b}
  resume(){this.init();this.ctx?.resume?.()}
  setVolumes(master,music,sfx){this.volumes={master:clamp(master,0,1),music:clamp(music,0,1),sfx:clamp(sfx,0,1)};this.applyVolumes()}
  setIntensity(v){this.targetIntensity=clamp(v,0,1)}
  applyVolumes(){if(!this.master||!this.sfx||!this.music)return;this.master.gain.value=this.volumes.master;this.sfx.gain.value=this.volumes.sfx;this.music.gain.value=this.volumes.music}
  tone(freq=100,duration=.08,amount=.2,type='sine',dest=null,pan=0,fall=.55){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner?.();o.type=type;o.frequency.setValueAtTime(freq,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(24,freq*fall),this.ctx.currentTime+duration);g.gain.setValueAtTime(Math.max(.001,amount),this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+duration);o.connect(g);if(p){p.pan.value=clamp(pan,-1,1);g.connect(p);p.connect(dest??this.sfx)}else g.connect(dest??this.sfx);o.start();o.stop(this.ctx.currentTime+duration)}
  noise(duration=.08,amount=.25,filterFreq=500,pan=0,type='lowpass'){if(!this.ctx||!this.sfx)return;const n=Math.max(1,Math.floor(this.ctx.sampleRate*duration)),buf=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const src=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner?.();src.buffer=buf;f.type=type;f.frequency.value=filterFreq;g.gain.value=amount;src.connect(f);f.connect(g);if(p){p.pan.value=clamp(pan,-1,1);g.connect(p);p.connect(this.sfx)}else g.connect(this.sfx);src.start()}
  whoosh(strength=.5,pan=0){this.resume();this.noise(.07+.08*strength,.025+.05*strength,900+1800*strength,pan,'bandpass');this.tone(240+strength*180,.055+.04*strength,.018+.025*strength,'sine',null,pan,.72)}
  ui(select=false){this.resume();this.tone(select?118:184,.045,.07,'square',null,0,.72);if(select)this.tone(236,.035,.025,'sine')}
  hit(kind='light',pan=0){this.resume();const k={light:[.06,.15,760,120],heavy:[.12,.34,420,72],grapple:[.14,.28,280,58],special:[.20,.46,620,40],environment:[.17,.42,240,48],weapon:[.13,.38,1350,86]}[kind]??[.08,.2,600,90];const strong=['heavy','grapple','special','environment','weapon'].includes(kind);this.whoosh(strong?.78:.42,pan);this.noise(k[0],k[1],k[2],pan);this.tone(k[3],k[0]*1.65,k[1]*.68,'triangle',null,pan,strong?.42:.58);if(strong)this.noise(.035,k[1]*.35,2500,pan,'highpass');if(kind==='heavy'||kind==='special'||kind==='environment'){this.tone(kind==='special'?34:46,.24,k[1]*.24,'sine',null,pan,.7);this.tone(kind==='special'?72:96,.11,k[1]*.12,'square',null,pan,.5)}}
  impact(kind='light',blocked=false,pan=0){if(blocked){this.resume();this.whoosh(.25,pan);this.tone(470,.045,.055,'square',null,pan,.82);this.noise(.045,.08,2800,pan,'highpass');this.tone(128,.08,.035,'triangle',null,pan,.6);return}this.hit(kind,pan);if(kind==='special')this.crowd(.95);else if(kind==='environment')this.crowd(.82);else if(['heavy','weapon','grapple'].includes(kind))this.crowd(.42)}
  pickup(){this.resume();this.tone(330,.05,.08,'square');setTimeout(()=>this.tone(440,.05,.07,'square'),45)}
  environment(){this.hit('environment');this.noise(.24,.09,160,'lowpass');this.crowd(.78)}
  ko(){this.resume();this.tone(70,.62,.5,'sawtooth',null,0,.45);this.noise(.34,.22,180);setTimeout(()=>this.tone(42,.86,.35,'triangle',null,0,.62),90);setTimeout(()=>this.noise(.26,.06,1100),140);this.crowd(1)}
  win(){this.ko();setTimeout(()=>{this.tone(132,.5,.2,'triangle');this.tone(198,.65,.11,'sine');this.tone(264,.42,.05,'sine');this.crowd(.85)},260)}
  special(){this.resume();this.tone(52,.72,.28,'sawtooth',null,0,.44);this.tone(108,.46,.18,'square');this.noise(.26,.13,1400);setTimeout(()=>this.whoosh(.95),80);this.crowd(.62)}
  crowd(intensity=.4){this.resume();const v=clamp(intensity,0,1);this.noise(.16+v*.24,.045+v*.10,760+v*420,0,'bandpass');this.noise(.20+v*.20,.025+v*.06,260+v*120,0,'lowpass');if(v>.7){this.tone(185+v*55,.10,.014+v*.014,'triangle',null,-.35,.86);this.tone(215+v*72,.12,.012+v*.012,'triangle',null,.35,.88)}}
  startMusic(){this.resume();this.musicOn=true;this.nextBeat=this.ctx?.currentTime??0;this.beatIndex=0}
  stopMusic(){this.musicOn=false}
  update(){if(!this.ctx)return;this.intensity+=(this.targetIntensity-this.intensity)*.035;if(!this.musicOn||!this.music)return;const now=this.ctx.currentTime,step=.52-this.intensity*.09;while(this.nextBeat<now+.12){const beat=this.beatIndex%8;this.kickAt(this.nextBeat,beat%4===0?.2+.05*this.intensity:.10+.04*this.intensity);if(beat%2===1)this.hatAt(this.nextBeat+step*.5);if(beat===2||beat===6)this.snareAt(this.nextBeat);if(beat%4===0)this.bassAt(this.nextBeat,beat===0?55:49);if(this.intensity>.62&&beat%2===0)this.hatAt(this.nextBeat+step*.25,.65);if(this.intensity>.78&&beat===7)this.riserAt(this.nextBeat,step);this.nextBeat+=step;this.beatIndex++}}
  kickAt(t,a){if(!this.ctx||!this.music)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(110,t);o.frequency.exponentialRampToValueAtTime(42,t+.13);g.gain.setValueAtTime(a,t);g.gain.exponentialRampToValueAtTime(.001,t+.14);o.connect(g);g.connect(this.music);o.start(t);o.stop(t+.15)}
  hatAt(t,mul=1){if(!this.ctx||!this.music)return;const n=512,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=Math.random()*2-1;const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='highpass';f.frequency.value=5000;g.gain.setValueAtTime(.035*mul,t);g.gain.exponentialRampToValueAtTime(.001,t+.04);s.connect(f);f.connect(g);g.connect(this.music);s.start(t)}
  snareAt(t){if(!this.ctx||!this.music)return;const n=Math.floor(this.ctx.sampleRate*.09),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=1600;g.gain.value=.07+.03*this.intensity;s.connect(f);f.connect(g);g.connect(this.music);s.start(t)}
  bassAt(t,freq){if(!this.ctx||!this.music)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o.frequency.value=freq;f.type='lowpass';f.frequency.value=180+this.intensity*160;g.gain.setValueAtTime(.025+.03*this.intensity,t);g.gain.exponentialRampToValueAtTime(.001,t+.38);o.connect(f);f.connect(g);g.connect(this.music);o.start(t);o.stop(t+.4)}
  riserAt(t,step){if(!this.ctx||!this.music)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o.frequency.setValueAtTime(72,t);o.frequency.exponentialRampToValueAtTime(150,t+step*.9);f.type='lowpass';f.frequency.setValueAtTime(240,t);f.frequency.exponentialRampToValueAtTime(900,t+step*.9);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(.018*this.intensity,t+step*.65);g.gain.exponentialRampToValueAtTime(.001,t+step);o.connect(f);f.connect(g);g.connect(this.music);o.start(t);o.stop(t+step)}
}
