import { ROSTER, getFighterDef } from '../data/roster.js';
import { ARENAS, getArenaDef } from '../data/arenas.js';
import { CIRCUIT } from '../data/career.js';
import { DEFAULT_SETTINGS, newCareer } from '../persistence/SaveStore.js';
import { NetSession } from '../multiplayer/NetSession.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>`${Math.max(0,Math.min(100,v))}%`;
const disclaimer='Fictional satirical fighting game. Public figures are presented as exaggerated game characters. No endorsement or affiliation is implied. George Floyd is portrayed only as a fictional game fighter and no real-world death is referenced.';

export class AppUI{
  constructor(root,game,store){this.root=root;this.game=game;this.store=store;this.career=null;this.settings={...DEFAULT_SETTINGS};this.lastConfig=null;this.net=null;this.paused=false;this.isTouch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0||innerWidth<900;this.hudEls={}}
  async init(){
    this.settings=await this.store.settings().catch(()=>({...DEFAULT_SETTINGS}));
    this.game.setHooks({onHud:m=>this.onHud(m),onMessage:t=>this.flash(t),onSpecial:(name,move)=>this.flash(`${name}: ${move}`),onEnd:m=>this.onEnd(m)});
    addEventListener('keydown',e=>{if(e.code==='Escape'&&this.game.match){e.preventDefault();this.togglePause()}});
    this.renderMenu();
  }
  set(html,cls=''){this.root.className=cls;this.root.innerHTML=html}
  topbar(meta=''){return `<div class="topbar"><div class="brand-word" aria-label="TWEAKIN"><span>TWEA</span><b>KIN</b></div><div class="kicker">Underground Fight Circuit</div><div class="topbar-spacer"></div><div class="top-meta">${esc(meta)}</div></div>`}
  pageHead(title,desc,back='menu'){return `<div class="page-head"><div><div class="page-title">${esc(title)}</div><div class="page-desc">${esc(desc)}</div></div><button class="back-btn interactive" data-back="${back}">BACK</button></div>`}
  bindBack(){this.root.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{this.game.audio.ui();const v=b.dataset.back;if(v==='career')this.renderCareerHub();else this.renderMenu()})}
  route(id){if(id==='battle')this.renderBattle();else if(id==='career')this.renderCareer();else if(id==='training')this.renderTraining();else if(id==='roster')this.renderRoster();else if(id==='options')this.renderOptions();else if(id==='credits')this.renderCredits();else if(id==='online')this.renderOnline();else this.renderMenu()}
  renderMenu(){
    this.game.stop();this.game.input.clearTouch();this.net?.close();this.net=null;this.game.setNetwork(null);this.paused=false;
    this.set(`<div class="screen menu-screen">${this.topbar(this.isTouch?'Mobile instant-play • touch controls':'Browser-native 3D fighting • Three.js')}<div class="menu-layout"><div class="menu-stack"><div class="eyebrow">TWEAKIN // FIGHT WORLD</div><h1 class="menu-heading">MAIN<br>MENU</h1><p class="menu-sub">Underground crossover fighting with career progression, environmental combat and eight distinct fighters.</p>${[['quick','Quick Fight'],['career','Career / Story'],['battle','Battle'],['online','Online P2P'],['training','Training'],['roster','Fighter Viewer'],['options','Options'],['credits','Credits']].map(([id,n])=>`<button class="menu-btn interactive ${id==='quick'?'quick-play':''}" data-nav="${id}">${n}</button>`).join('')}</div><div class="menu-art"><div class="silhouette-wall">${ROSTER.slice(0,6).map((f,i)=>`<div class="menu-sil" style="--skin:#${f.palette.skin.toString(16).padStart(6,'0')};--cloth:#${f.palette.primary.toString(16).padStart(6,'0')};--i:${i}"><i></i><b></b></div>`).join('')}</div><div class="menu-art-copy"><span>8 FIGHTERS</span><span>12 VENUES</span><span>CAREER + P2P</span></div></div></div><div class="bottom-disclaimer">${disclaimer}</div></div>`,'menu');
    this.root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{this.game.audio.ui(true);const n=b.dataset.nav;if(n==='quick')this.quickFight();else this.route(n)});
  }
  quickFight(){
    const player=ROSTER[Math.floor(Math.random()*ROSTER.length)], opponents=ROSTER.filter(x=>x.id!==player.id), enemy=opponents[Math.floor(Math.random()*opponents.length)], arena=ARENAS[Math.floor(Math.random()*Math.min(ARENAS.length,8))];
    this.startFight({mode:'quick',matchType:'One on One',arenaId:arena.id,fighters:[player.id,enemy.id],humanSlots:[0],aiDifficulty:.66,roundSeconds:120});
  }
  fighterCards(selected=''){return ROSTER.map(f=>`<button class="card roster-card interactive ${selected===f.id?'active':''}" data-fighter="${f.id}" style="--accent:#${f.palette.accent.toString(16).padStart(6,'0')};--skin:#${f.palette.skin.toString(16).padStart(6,'0')};--cloth:#${f.palette.primary.toString(16).padStart(6,'0')}"><div class="fighter-silhouette"><span class="head"></span><span class="body"></span><span class="legs"></span></div><div class="card-copy"><div class="card-kicker">${esc(f.archetype)}</div><h3>${esc(f.shortName)}</h3><p>${esc(f.styles.join(' + '))}</p></div></button>`).join('')}
  statMarkup(stats){return Object.entries(stats).map(([k,v])=>`<div class="statbar"><span>${esc(k.replace(/([A-Z])/g,' $1'))}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`).join('')}
  renderBattle(){
    let p1='trump',p2='gigachad',arena='underpass',type='One on One',difficulty=.65;
    this.set(`<div class="panel-screen">${this.pageHead('Battle','Build a custom one-on-one fight with arena, rules and AI difficulty.')}<div class="content-scroll"><div class="battle-grid"><div><div class="section-label">PLAYER</div><div class="grid fighter-grid" id="p1-grid">${this.fighterCards(p1)}</div></div><div><div class="section-label">OPPONENT</div><div class="grid fighter-grid" id="p2-grid">${this.fighterCards(p2)}</div></div></div><div class="detail-panel setup-panel"><div class="setup-row"><label>Venue<select id="arena-select">${ARENAS.map(a=>`<option value="${a.id}">${esc(a.name)} — ${esc(a.archetype)}</option>`).join('')}</select></label><label>Rule<select id="type-select">${['One on One','Ring Out','Demolition','Subway','Window','Cage','Inferno'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>AI<select id="diff-select"><option value=".4">Normal</option><option value=".65" selected>Hard</option><option value=".84">Brutal</option><option value="1">TWEAKIN</option></select></label></div><div class="action-row"><button id="battle-start" class="primary-action interactive">START FIGHT</button></div></div></div></div>`,'battle');
    this.bindBack();
    const bind=(sel,which)=>this.root.querySelector(sel).querySelectorAll('[data-fighter]').forEach(b=>b.onclick=()=>{this.root.querySelector(sel).querySelectorAll('[data-fighter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(which===1)p1=b.dataset.fighter;else p2=b.dataset.fighter;this.game.audio.ui(true)});bind('#p1-grid',1);bind('#p2-grid',2);
    this.root.querySelector('#battle-start').onclick=()=>{arena=this.root.querySelector('#arena-select').value;type=this.root.querySelector('#type-select').value;difficulty=Number(this.root.querySelector('#diff-select').value);if(p1===p2)p2=ROSTER.find(x=>x.id!==p1).id;this.startFight({mode:'battle',matchType:type,arenaId:arena,fighters:[p1,p2],humanSlots:[0],aiDifficulty:difficulty,roundSeconds:180})};
  }
  async renderCareer(){
    this.career=await this.store.career();
    if(this.career){this.renderCareerHub();return}
    let selected='trump';
    this.set(`<div class="panel-screen">${this.pageHead('Career / Story','Choose your fighter and enter the TWEAKIN underground circuit. Progress saves automatically.')}<div class="content-scroll"><div class="grid fighter-grid" id="career-grid">${this.fighterCards(selected)}</div><div class="action-row sticky-action"><button id="career-start" class="primary-action interactive">START CAREER AS TRUMP</button></div></div></div>`,'career-select');this.bindBack();
    this.root.querySelectorAll('#career-grid [data-fighter]').forEach(b=>b.onclick=()=>{selected=b.dataset.fighter;this.root.querySelectorAll('#career-grid [data-fighter]').forEach(x=>x.classList.toggle('active',x===b));this.root.querySelector('#career-start').textContent=`START CAREER AS ${getFighterDef(selected).shortName}`});
    this.root.querySelector('#career-start').onclick=async()=>{this.career=newCareer(selected);await this.store.saveCareer(this.career);this.renderCareerHub()};
  }
  renderCareerHub(){
    const c=this.career,f=getFighterDef(c.fighterId),bout=CIRCUIT[c.circuitIndex],done=!bout;
    this.set(`<div class="panel-screen career-screen">${this.pageHead('Career Hub',`${f.name} • ${c.wins}W ${c.losses}L • £${c.credits.toLocaleString()} • ${c.development} DP`)}<div class="content-scroll"><div class="split"><div class="detail-panel feature-panel"><div class="section-label">${done?'CIRCUIT COMPLETE':'NEXT FIGHT'}</div><h2>${done?'CHAMPION':esc(bout.title)}</h2><p>${done?'You cleared the current underground circuit. Replay Battle mode or reset the career for another run.':esc(bout.message)}</p>${!done?`<div class="meta"><span class="tag">${getArenaDef(bout.arenaId).name}</span><span class="tag">VS ${getFighterDef(bout.opponent).shortName}</span><span class="tag">£${bout.reward}</span><span class="tag">+${bout.dev} DP</span></div><div class="action-row"><button id="career-fight" class="primary-action interactive">ENTER FIGHT</button></div>`:''}</div><div class="detail-panel"><div class="section-label">FIGHTER DEVELOPMENT</div>${this.statMarkup(c.stats)}<div class="action-row"><button id="train-upper" class="secondary-action interactive" ${c.development<1?'disabled':''}>UPPER BODY +3</button><button id="train-speed" class="secondary-action interactive" ${c.development<1?'disabled':''}>SPEED +3</button><button id="train-tough" class="secondary-action interactive" ${c.development<1?'disabled':''}>TOUGHNESS +3</button></div></div></div><div class="grid hub-grid"><article class="card"><h3>Styles</h3><p>${esc(c.learnedStyles.join(' + '))}</p><div class="action-row"><button id="learn-style" class="secondary-action interactive" ${c.development<2?'disabled':''}>LEARN SUBMISSIONS • 2 DP</button></div></article><article class="card"><h3>Wardrobe</h3><p>${c.cosmetics.length?esc(c.cosmetics.join(', ')):'No purchased presentation pieces yet.'}</p><div class="action-row"><button id="buy-chain" class="secondary-action interactive" ${c.credits<650?'disabled':''}>STEEL CHAIN • £650</button></div></article><article class="card"><h3>Messages</h3><p>${esc(c.messages.at(-1)?.text??'No new messages.')}</p></article><article class="card"><h3>Save</h3><p>Career is stored locally in IndexedDB.</p><div class="action-row"><button id="reset-career" class="secondary-action interactive">RESET CAREER</button></div></article></div></div></div>`,'career');this.bindBack();
    this.root.querySelector('#career-fight')?.addEventListener('click',()=>this.startCareerFight());
    const spend=async key=>{if(c.development<1)return;c.development--;c.stats[key]=Math.min(100,c.stats[key]+3);await this.store.saveCareer(c);this.renderCareerHub()};this.root.querySelector('#train-upper')?.addEventListener('click',()=>spend('upperBody'));this.root.querySelector('#train-speed')?.addEventListener('click',()=>spend('speed'));this.root.querySelector('#train-tough')?.addEventListener('click',()=>spend('toughness'));
    this.root.querySelector('#learn-style')?.addEventListener('click',async()=>{if(c.development<2||c.learnedStyles.includes('Submissions'))return;c.development-=2;c.learnedStyles.push('Submissions');await this.store.saveCareer(c);this.renderCareerHub()});
    this.root.querySelector('#buy-chain')?.addEventListener('click',async()=>{if(c.credits<650||c.cosmetics.includes('Steel Chain'))return;c.credits-=650;c.cosmetics.push('Steel Chain');c.charismaBonus+=3;await this.store.saveCareer(c);this.renderCareerHub()});
    this.root.querySelector('#reset-career')?.addEventListener('click',async()=>{if(confirm('Reset this TWEAKIN career?')){await this.store.resetCareer();this.career=null;this.renderCareer()}});
  }
  startCareerFight(){const c=this.career,b=CIRCUIT[c.circuitIndex];if(!b)return;this.startFight({mode:'career',matchType:b.matchType,arenaId:b.arenaId,fighters:[c.fighterId,b.opponent],humanSlots:[0],aiDifficulty:.48+c.circuitIndex*.065,roundSeconds:180,fighterOverrides:{0:{stats:{...c.stats},styles:[...c.learnedStyles]}}})}
  async resolveCareer(match){if(!this.career||match.config.mode!=='career')return;const b=CIRCUIT[this.career.circuitIndex];if(!b)return;const won=match.winner?.slot===0;if(won){this.career.wins++;this.career.credits+=b.reward;this.career.development+=b.dev;this.career.circuitIndex++;if(b.unlockArena&&!this.career.unlockedArenas.includes(b.unlockArena))this.career.unlockedArenas.push(b.unlockArena);if(b.unlockMatch&&!this.career.unlockedMatchTypes.includes(b.unlockMatch))this.career.unlockedMatchTypes.push(b.unlockMatch);this.career.messages.push({id:`m${Date.now()}`,text:`${b.title} cleared. Payment received. The circuit moves you forward.`,read:false})}else{this.career.losses++;this.career.messages.push({id:`m${Date.now()}`,text:`Loss recorded at ${b.title}. The circuit is still open. Run it back.`,read:false})}await this.store.saveCareer(this.career)}
  renderTraining(){
    let selected='trump';
    this.set(`<div class="panel-screen">${this.pageHead('Training','Infinite timer, passive opponent and instant momentum for learning controls.')}<div class="content-scroll"><div class="grid fighter-grid" id="training-grid">${this.fighterCards(selected)}</div><div class="action-row sticky-action"><button id="training-start" class="primary-action interactive">ENTER TRAINING</button></div></div></div>`,'training');this.bindBack();this.root.querySelectorAll('#training-grid [data-fighter]').forEach(b=>b.onclick=()=>{selected=b.dataset.fighter;this.root.querySelectorAll('#training-grid [data-fighter]').forEach(x=>x.classList.toggle('active',x===b))});this.root.querySelector('#training-start').onclick=()=>this.startFight({mode:'training',matchType:'Training',arenaId:'iron-gym',fighters:[selected,'wojak'],humanSlots:[0],aiDifficulty:.12,roundSeconds:9999});
  }
  renderRoster(){
    let selected=ROSTER[0];
    const detail=()=>`<div class="fighter-detail"><div class="fighter-hero" style="--accent:#${selected.palette.accent.toString(16).padStart(6,'0')};--skin:#${selected.palette.skin.toString(16).padStart(6,'0')};--cloth:#${selected.palette.primary.toString(16).padStart(6,'0')}"><div class="giant-sil"><i></i><b></b><em></em></div></div><div class="detail-panel"><div class="section-label">${esc(selected.archetype)}</div><h2>${esc(selected.name)}</h2><p>${esc(selected.description)}</p><div class="meta"><span class="tag">${esc(selected.styles.join(' + '))}</span><span class="tag">${esc(selected.wardrobe)}</span></div>${this.statMarkup(selected.stats)}<div class="finisher-list">${selected.finishers.map(x=>`<div><b>${esc(x.name)}</b><span>${esc(x.flavour)}</span></div>`).join('')}</div></div></div>`;
    this.set(`<div class="panel-screen">${this.pageHead('Fighter Viewer','Eight deliberately different silhouettes, archetypes, stats and finishers.')}<div class="content-scroll"><div class="roster-browser"><div class="roster-list">${ROSTER.map((f,i)=>`<button class="roster-row interactive ${i===0?'active':''}" data-rid="${f.id}"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(f.shortName)}</b><em>${esc(f.archetype)}</em></button>`).join('')}</div><div id="roster-detail">${detail()}</div></div></div></div>`,'roster');this.bindBack();this.root.querySelectorAll('[data-rid]').forEach(b=>b.onclick=()=>{selected=getFighterDef(b.dataset.rid);this.root.querySelectorAll('[data-rid]').forEach(x=>x.classList.toggle('active',x===b));this.root.querySelector('#roster-detail').innerHTML=detail();this.game.audio.ui(true)});
  }
  async renderOptions(){
    const s={...this.settings};
    this.set(`<div class="panel-screen">${this.pageHead('Options','Audio, camera and rendering settings.')}<div class="content-scroll"><div class="detail-panel options-panel"><label>Master Volume <input id="master" type="range" min="0" max="1" step=".01" value="${s.masterVolume}"></label><label>Music Volume <input id="music" type="range" min="0" max="1" step=".01" value="${s.musicVolume}"></label><label>SFX Volume <input id="sfx" type="range" min="0" max="1" step=".01" value="${s.sfxVolume}"></label><label>Camera Shake <input id="shake" type="range" min="0" max="1" step=".01" value="${s.cameraShake}"></label><label>Quality <select id="quality"><option value="low" ${s.quality==='low'?'selected':''}>Low / Mobile</option><option value="medium" ${s.quality==='medium'?'selected':''}>Medium</option><option value="high" ${s.quality==='high'?'selected':''}>High</option></select></label><label class="check"><input id="reduce" type="checkbox" ${s.reducedMotion?'checked':''}> Reduced motion</label><div class="action-row"><button id="save-options" class="primary-action interactive">SAVE OPTIONS</button></div></div></div></div>`,'options');this.bindBack();this.root.querySelector('#save-options').onclick=async()=>{this.settings={...s,masterVolume:Number(this.root.querySelector('#master').value),musicVolume:Number(this.root.querySelector('#music').value),sfxVolume:Number(this.root.querySelector('#sfx').value),cameraShake:Number(this.root.querySelector('#shake').value),quality:this.root.querySelector('#quality').value,reducedMotion:this.root.querySelector('#reduce').checked};await this.store.saveSettings(this.settings);this.game.updateSettings(this.settings);this.renderMenu()};
  }
  renderCredits(){this.set(`<div class="panel-screen">${this.pageHead('Credits','Original browser-native TWEAKIN build.')}<div class="content-scroll"><div class="split"><div class="detail-panel"><div class="section-label">BUILD</div><h2>TWEAKIN</h2><p>Three.js/WebGL runtime, procedural fighters, procedural arenas, Web Audio soundtrack and IndexedDB progression.</p><div class="meta"><span class="tag">MOBILE</span><span class="tag">DESKTOP</span><span class="tag">P2P WEBRTC</span></div></div><div class="detail-panel"><div class="section-label">CONTENT NOTE</div><p>${disclaimer}</p></div></div></div></div>`,'credits');this.bindBack()}
  renderOnline(){
    this.net?.close();this.net=new NetSession();
    this.set(`<div class="panel-screen">${this.pageHead('Online P2P','Manual WebRTC pairing. No account or server required: host creates an offer code, guest creates an answer code.')}<div class="content-scroll"><div class="split"><div class="detail-panel"><div class="section-label">HOST</div><p>Create a pairing code, send it to the other player, then paste their answer back here.</p><div class="action-row"><button id="make-offer" class="primary-action interactive">CREATE OFFER</button></div><textarea id="offer-out" readonly placeholder="Offer code appears here"></textarea><textarea id="answer-in" placeholder="Paste guest answer here"></textarea><div class="action-row"><button id="accept-answer" class="secondary-action interactive">ACCEPT ANSWER</button><button id="host-start" class="primary-action interactive" disabled>START ONLINE FIGHT</button></div></div><div class="detail-panel"><div class="section-label">JOIN</div><p>Paste the host offer and generate an answer. Send the answer back to the host.</p><textarea id="offer-in" placeholder="Paste host offer here"></textarea><div class="action-row"><button id="join-offer" class="primary-action interactive">CREATE ANSWER</button></div><textarea id="answer-out" readonly placeholder="Answer code appears here"></textarea><div id="net-status" class="network-status">STATUS: IDLE</div></div></div></div></div>`,'online');this.bindBack();
    const status=()=>{const el=this.root.querySelector('#net-status');if(el)el.textContent=`STATUS: ${this.net.status.toUpperCase()}${this.net.connected?' • CONNECTED':''}`;const start=this.root.querySelector('#host-start');if(start)start.disabled=!this.net.connected};const ticker=setInterval(()=>{if(!this.root.isConnected||!this.root.querySelector('#net-status')){clearInterval(ticker);return}status()},400);
    this.root.querySelector('#make-offer').onclick=async()=>{try{this.root.querySelector('#offer-out').value=await this.net.createOffer();status()}catch(e){alert(`WebRTC offer failed: ${e.message}`)}};
    this.root.querySelector('#join-offer').onclick=async()=>{try{const code=this.root.querySelector('#offer-in').value.trim();this.root.querySelector('#answer-out').value=await this.net.acceptOffer(code);this.game.setNetwork(this.net);this.net.onMatchConfig=cfg=>this.startFight(cfg,true);status()}catch(e){alert(`WebRTC join failed: ${e.message}`)}};
    this.root.querySelector('#accept-answer').onclick=async()=>{try{await this.net.acceptAnswer(this.root.querySelector('#answer-in').value.trim());this.game.setNetwork(this.net);status()}catch(e){alert(`WebRTC answer failed: ${e.message}`)}};
    this.root.querySelector('#host-start').onclick=()=>{const enemy=ROSTER[Math.floor(Math.random()*ROSTER.length)],cfg={mode:'online',matchType:'Online One on One',arenaId:'underpass',fighters:['trump',enemy.id==='trump'?'gigachad':enemy.id],humanSlots:[0,1],aiDifficulty:.1,roundSeconds:180};this.net.broadcastMatchConfig(cfg);this.startFight(cfg,true)};
  }
  touchMarkup(){if(!this.isTouch)return'';return `<div id="mobile-touch" class="mobile-touch interactive"><button id="touch-pause" class="touch-pause interactive" aria-label="Pause">Ⅱ</button><div class="touch-stick-wrap"><div id="touch-stick" class="touch-stick interactive"><div class="touch-stick-ring"></div><div class="touch-stick-knob"></div><span>MOVE</span></div></div><div class="touch-actions"><div class="touch-utility"><button class="touch-mini interactive" data-touch="taunt">SPECIAL</button><button class="touch-mini interactive" data-touch="pickup">WEAPON</button><button class="touch-mini interactive" data-touch="run">RUN</button></div><div class="touch-face"><button class="touch-btn touch-light interactive" data-touch="light"><b>L</b><span>LIGHT</span></button><button class="touch-btn touch-heavy interactive" data-touch="heavy"><b>H</b><span>HEAVY</span></button><button class="touch-btn touch-grapple interactive" data-touch="grapple"><b>G</b><span>GRAB</span></button><button class="touch-btn touch-block interactive" data-touch="block"><b>B</b><span>BLOCK</span></button></div></div><div class="rotate-note">LANDSCAPE RECOMMENDED</div></div>`}
  bindTouchControls(){
    if(!this.isTouch)return;const stick=this.root.querySelector('#touch-stick'),knob=stick?.querySelector('.touch-stick-knob');let active=-1;
    const move=e=>{if(!stick||!knob)return;const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,rad=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy;const d=Math.hypot(dx,dy);if(d>rad){dx*=rad/d;dy*=rad/d}knob.style.transform=`translate(${dx}px,${dy}px)`;this.game.input.setTouchAxis(dx/rad,dy/rad)};
    stick?.addEventListener('pointerdown',e=>{e.preventDefault();active=e.pointerId;stick.setPointerCapture?.(active);move(e)});stick?.addEventListener('pointermove',e=>{if(e.pointerId===active)move(e)});const release=e=>{if(e.pointerId!==active)return;active=-1;if(knob)knob.style.transform='translate(0,0)';this.game.input.setTouchAxis(0,0)};stick?.addEventListener('pointerup',release);stick?.addEventListener('pointercancel',release);
    this.root.querySelectorAll('[data-touch]').forEach(b=>{const action=b.dataset.touch;const down=e=>{e.preventDefault();b.classList.add('pressed');this.game.input.setTouchButton(action,true);navigator.vibrate?.(8)};const up=e=>{e.preventDefault();b.classList.remove('pressed');this.game.input.setTouchButton(action,false)};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',e=>{if(e.buttons===0)up(e)})});this.root.querySelector('#touch-pause')?.addEventListener('click',()=>this.togglePause());
  }
  startFight(config,networkAlready=false){
    this.lastConfig=config;this.game.input.clearTouch();if(!networkAlready&&config.mode!=='online'){this.game.setNetwork(null)}
    this.set(`<div class="hud" id="hud"><div class="hud-top"><div class="hud-fighter" id="hud-p1"><div class="hud-name"></div><div class="health-shell"><div class="health-physical"></div><div class="health-conscious"></div></div><div class="momentum-shell"><div class="momentum"></div></div></div><div class="hud-center"><div class="round-label">${esc(config.matchType)}</div><div class="timer">${config.roundSeconds>=9999?'∞':'3:00'}</div></div><div class="hud-fighter right" id="hud-p2"><div class="hud-name"></div><div class="health-shell"><div class="health-physical"></div><div class="health-conscious"></div></div><div class="momentum-shell"><div class="momentum"></div></div></div></div><div class="hud-bottom"><div class="control-hint">WASD move • J light • K heavy • L grapple • I block • U special • O weapon • Esc pause</div><div class="control-hint" id="hud-state"></div></div><div class="fight-message">FIGHT</div>${this.touchMarkup()}<div id="pause-overlay" class="pause-overlay"><div class="pause-card"><h2>PAUSED</h2><button id="resume-fight" class="primary-action interactive">RESUME</button><button id="quit-fight" class="secondary-action interactive">QUIT TO MENU</button></div></div></div>`,'fight');
    this.hudEls={p1:this.root.querySelector('#hud-p1'),p2:this.root.querySelector('#hud-p2'),timer:this.root.querySelector('.timer'),state:this.root.querySelector('#hud-state')};this.bindTouchControls();this.root.querySelector('#resume-fight').onclick=()=>this.togglePause(false);this.root.querySelector('#quit-fight').onclick=()=>this.renderMenu();setTimeout(()=>this.root.querySelector('.fight-message')?.remove(),800);this.game.start(config);this.game.audio.resume();
    if(this.isTouch){document.documentElement.requestFullscreen?.().catch(()=>{});screen.orientation?.lock?.('landscape').catch?.(()=>{})}
  }
  togglePause(force){if(!this.game.match)return;this.paused=force??!this.paused;this.game.setPaused(this.paused);this.root.querySelector('#pause-overlay')?.classList.toggle('show',this.paused);this.game.input.clearTouch()}
  onHud(m){
    const setSide=(el,f)=>{if(!el||!f)return;el.querySelector('.hud-name').textContent=f.def.shortName;el.querySelector('.health-physical').style.width=pct(f.physical);el.querySelector('.health-conscious').style.width=pct(f.consciousness);el.querySelector('.momentum').style.width=pct(f.momentum);el.classList.toggle('danger',f.danger());el.classList.toggle('special-ready',f.momentum>=100||f.specialTime>0)};setSide(this.hudEls.p1,m.fighters[0]);setSide(this.hudEls.p2,m.fighters[1]);if(this.hudEls.timer)this.hudEls.timer.textContent=m.remaining>999? '∞':`${Math.floor(m.remaining/60)}:${String(Math.floor(m.remaining%60)).padStart(2,'0')}`;if(this.hudEls.state)this.hudEls.state.textContent=`${m.arena.def.name} • ${Math.round(this.game.fps)} FPS`;
  }
  flash(text){let el=this.root.querySelector('.fight-toast');if(!el){el=document.createElement('div');el.className='fight-toast';this.root.appendChild(el)}el.textContent=text;el.classList.remove('show');requestAnimationFrame(()=>el.classList.add('show'));clearTimeout(this.flashTimer);this.flashTimer=setTimeout(()=>el.classList.remove('show'),750)}
  async onEnd(match){
    if(!match)return;if(match.config.mode==='career')await this.resolveCareer(match);const w=match.winner;
    this.root.insertAdjacentHTML('beforeend',`<div class="result-shell"><div class="result-card"><div class="section-label">${esc(match.config.matchType)}</div><h2>${w?`${esc(w.def.shortName)} WINS`:'DRAW'}</h2><p>${esc(match.arena.def.name)} • ${Math.floor(match.elapsed)} seconds • ${match.fighters.reduce((a,f)=>a+f.combo,0)} combo events</p><div class="action-row"><button id="result-rematch" class="primary-action interactive">REMATCH</button><button id="result-exit" class="secondary-action interactive">${match.config.mode==='career'?'CAREER HUB':'MAIN MENU'}</button></div></div></div>`);
    this.root.querySelector('#result-rematch').onclick=()=>this.startFight(this.lastConfig,match.config.mode==='online');this.root.querySelector('#result-exit').onclick=()=>match.config.mode==='career'?this.renderCareerHub():this.renderMenu();
  }
}
