import { ROSTER } from '../data/roster.js';
import { ARENAS } from '../data/arenas.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function installUIEnhancements(AppUI){
  if(AppUI.prototype.__tweakinEnhanced)return;AppUI.prototype.__tweakinEnhanced=true;
  const originalMenu=AppUI.prototype.renderMenu,originalStart=AppUI.prototype.startFight;
  AppUI.prototype.renderMenu=function(){
    originalMenu.call(this);const stack=this.root.querySelector('.menu-stack');if(!stack)return;const anchor=stack.querySelector('[data-nav="online"]')||stack.querySelector('[data-nav="training"]');
    const chaos=document.createElement('button');chaos.className='menu-btn interactive premium-mode';chaos.textContent='Chaos FFA';chaos.onclick=()=>{this.game.audio.ui(true);this.startChaosFight()};stack.insertBefore(chaos,anchor);
    if(!this.isTouch){const versus=document.createElement('button');versus.className='menu-btn interactive premium-mode';versus.textContent='Local Versus';versus.onclick=()=>{this.game.audio.ui(true);this.renderLocalVersus()};stack.insertBefore(versus,anchor)}
    const guide=document.createElement('button');guide.className='menu-btn interactive';guide.textContent='Fight Guide';guide.onclick=()=>{this.game.audio.ui();this.renderFightGuide()};const credits=stack.querySelector('[data-nav="credits"]');stack.insertBefore(guide,credits||null);
  };
  AppUI.prototype.startChaosFight=function(){const shuffled=[...ROSTER].sort(()=>Math.random()-.5),fighters=shuffled.slice(0,4),arena=ARENAS[Math.floor(Math.random()*ARENAS.length)];this.startFight({mode:'chaos',matchType:'4-Way Chaos',arenaId:arena.id,fighters:fighters.map(f=>f.id),humanSlots:[0],aiDifficulty:.74,roundSeconds:210})};
  AppUI.prototype.renderLocalVersus=function(){
    let p1=ROSTER[0].id,p2=ROSTER[5]?.id??ROSTER[1].id,arena=ARENAS[0].id;this.set(`<div class="panel-screen local-versus">${this.pageHead('Local Versus','Two players. One screen. Keyboard or gamepads.')}<div class="content-scroll"><div class="versus-select"><div><div class="section-label">PLAYER ONE</div><div class="grid fighter-grid mini-grid" id="local-p1">${this.fighterCards(p1)}</div></div><div><div class="section-label">PLAYER TWO</div><div class="grid fighter-grid mini-grid" id="local-p2">${this.fighterCards(p2)}</div></div></div><div class="detail-panel setup-panel"><div class="setup-row"><label>Venue<select id="local-arena">${ARENAS.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><div class="local-controls"><b>P1</b><span>WASD • J/K/L • I block • Shift run • U special</span></div><div class="local-controls"><b>P2</b><span>Arrows • Num 1/2/3 • Num 0 block • Enter run</span></div></div><div class="action-row"><button id="local-start" class="primary-action interactive">START LOCAL FIGHT</button></div></div></div></div>`,'local-versus-screen');this.bindBack();
    const bind=(sel,key)=>this.root.querySelector(sel)?.querySelectorAll('[data-fighter]').forEach(b=>b.onclick=()=>{this.root.querySelector(sel).querySelectorAll('[data-fighter]').forEach(x=>x.classList.toggle('active',x===b));if(key===1)p1=b.dataset.fighter;else p2=b.dataset.fighter;this.game.audio.ui(true)});bind('#local-p1',1);bind('#local-p2',2);
    this.root.querySelector('#local-start').onclick=()=>{arena=this.root.querySelector('#local-arena').value;if(p1===p2)p2=ROSTER.find(f=>f.id!==p1).id;this.startFight({mode:'local',matchType:'Local Versus',arenaId:arena,fighters:[p1,p2],humanSlots:[0,1],aiDifficulty:.1,roundSeconds:180})};
  };
  AppUI.prototype.renderFightGuide=function(){
    const mobile=this.isTouch;this.set(`<div class="panel-screen fight-guide">${this.pageHead('Fight Guide','The systems that separate button-mashing from winning.')}<div class="content-scroll"><div class="guide-hero detail-panel"><div><div class="section-label">CORE LOOP</div><h2>HURT THE BODY.<br>BREAK THE FOCUS.</h2><p>Physical condition and consciousness are separate. Heavy strikes, grapples, weapons and the environment create the biggest openings. Build momentum, then spend a full meter on your fighter's special sequence.</p></div><div class="guide-meter"><span>CONSCIOUSNESS</span><i></i><span>PHYSICAL</span><i></i><span>MOMENTUM</span><i></i></div></div><div class="guide-grid"><article class="detail-panel"><div class="section-label">OFFENCE</div><h3>CHAIN ATTACKS</h3><p>Light is fast pressure. Heavy has wind-up but creates knockdowns. Grab beats passive defence. Attack inputs are buffered late in animations so combinations feel responsive.</p></article><article class="detail-panel"><div class="section-label">DEFENCE</div><h3>PARRY & EVADE</h3><p>Tap Block just before a normal strike lands to parry and stun the attacker. Hold Block + Run + movement to evade with a short invulnerability window.</p></article><article class="detail-panel"><div class="section-label">WORLD</div><h3>USE THE ROOM</h3><p>Pick up nearby weapons, drive opponents toward environmental anchors, break panels, and respect each venue's hazard rules.</p></article><article class="detail-panel"><div class="section-label">SPECIAL</div><h3>FULL MOMENTUM</h3><p>At 100 momentum use Special. The camera cuts closer, your fighter enters their signature sequence, and clean contact can decide a fight.</p></article></div><div class="detail-panel controls-guide"><div class="section-label">${mobile?'TOUCH CONTROLS':'KEYBOARD / GAMEPAD'}</div>${mobile?`<div class="controls-map"><span><b>LEFT STICK</b>Move / position</span><span><b>LIGHT</b>Fast strike</span><span><b>HEAVY</b>Power strike</span><span><b>GRAB</b>Grapple</span><span><b>BLOCK</b>Guard / tap to parry</span><span><b>RUN + BLOCK + MOVE</b>Evade</span><span><b>SPECIAL</b>Use full momentum</span><span><b>WEAPON</b>Pick up nearby object</span></div>`:`<div class="controls-map"><span><b>WASD</b>Move</span><span><b>J / K / L</b>Light / Heavy / Grab</span><span><b>I</b>Block / tap to parry</span><span><b>SHIFT + I + MOVE</b>Evade</span><span><b>U</b>Special</span><span><b>O</b>Weapon</span><span><b>GAMEPAD</b>Left stick + face buttons</span></div>`}</div></div></div>`,'fight-guide-screen');this.bindBack();
  };
  AppUI.prototype.startFight=function(config,networkAlready=false){originalStart.call(this,config,networkAlready);const hint=this.root.querySelector('.control-hint');if(hint&&!this.isTouch)hint.textContent='WASD move • J light • K heavy • L grab • I block/parry • Shift + I + move evade • U special • O weapon';const state=this.root.querySelector('#hud-state');if(state&&this.isTouch)state.dataset.tip='Tap Block on impact to parry • Block + Run + move to evade'};
}
